# Generated by Django 6.0.3 on 2026-04-28 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrackRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash', models.CharField(db_index=True, max_length=32)),
                ('max_length', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('READY', 'Ready'), ('ERROR', 'Error')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('part_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CrackPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField()),
                ('part_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='api.crackrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['request', 'status'], name='api_crackpa_request_ffaf2e_idx')],
                'constraints': [models.UniqueConstraint(fields=('request', 'part_number'), name='uniq_part_per_request')],
            },
        ),
        migrations.CreateModel(
            name='CrackResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.crackrequest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('request', 'word'), name='uniq_word_per_request')],
            },
        ),
    ]
